"""Add order field to SavedDay

Revision ID: 21e304747332
Revises: 36bae68572d7
Create Date: 2025-04-27 17:55:25.133557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e304747332'
down_revision = '36bae68572d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_day', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
    
    # Set default values for existing rows
    connection = op.get_bind()
    connection.execute(
        sa.text("""
            UPDATE saved_day 
            SET "order" = subquery.row_num 
            FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY saved_plan_id ORDER BY id) as row_num 
                FROM saved_day
            ) as subquery 
            WHERE saved_day.id = subquery.id
        """)
    )
    
    # Now make the column non-nullable
    with op.batch_alter_table('saved_day', schema=None) as batch_op:
        batch_op.alter_column('order', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_day', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
