"""Updated order attribute to log models

Revision ID: 2b32b334fd2d
Revises: 303504c15aa9
Create Date: 2025-05-20 11:20:46.837788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b32b334fd2d'
down_revision = '303504c15aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='workout_preferences_user_id_key')
    )
    # ### end Alembic commands ###
