"""Updated name change

Revision ID: 36bae68572d7
Revises: 87fbfe94c546
Create Date: 2025-04-27 15:17:48.724569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bae68572d7'
down_revision = '87fbfe94c546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('exercise_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
