"""Create Equipment model and update Exercise model

Revision ID: 3a0dff74ce0c
Revises: e09f9c8b43c7
Create Date: 2025-04-23 17:11:15.918855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a0dff74ce0c'
down_revision = 'e09f9c8b43c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'])
        batch_op.drop_column('equipment')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('COMPOUND', 'ISOLATION', name='exercise_type_enum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('equipment', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipment_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('BARBELL', 'DUMBBELL', 'BODYWEIGHT', 'MACHINE', 'CABLE', name='equipment_type_enum'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
