"""added notes to saved exercise

Revision ID: 5761b37f8410
Revises: 21e304747332
Create Date: 2025-04-28 12:51:56.809223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5761b37f8410'
down_revision = '21e304747332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
