"""Added workout logging models

Revision ID: 579a0f2402d9
Revises: baf6600c8ab8
Create Date: 2025-05-16 20:22:54.401528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579a0f2402d9'
down_revision = 'baf6600c8ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='workout_preferences_user_id_key')
    )
    # ### end Alembic commands ###
