"""Rename Logging models

Revision ID: 69e38aa57210
Revises: 579a0f2402d9
Create Date: 2025-05-18 20:39:28.047665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e38aa57210'
down_revision = '579a0f2402d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_preferences')
    with op.batch_alter_table('logged_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logged_week_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('workout_log_weekly_log_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logged_week', ['logged_week_id'], ['id'])
        batch_op.drop_column('weekly_log_id')

    with op.batch_alter_table('logged_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logged_day_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('logged_exercise_workout_log_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logged_day', ['logged_day_id'], ['id'])
        batch_op.drop_column('workout_log_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_log_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('logged_exercise_workout_log_id_fkey', 'logged_day', ['workout_log_id'], ['id'])
        batch_op.drop_column('logged_day_id')

    with op.batch_alter_table('logged_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_log_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('workout_log_weekly_log_id_fkey', 'logged_week', ['weekly_log_id'], ['id'])
        batch_op.drop_column('logged_week_id')

    op.create_table('workout_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='workout_preferences_user_id_key')
    )
    # ### end Alembic commands ###
