"""Updated saved exercise to include name

Revision ID: 87fbfe94c546
Revises: dd75128522f5
Create Date: 2025-04-27 15:17:08.501994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fbfe94c546'
down_revision = 'dd75128522f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.drop_column('exercise_name')

    # ### end Alembic commands ###
