"""Replace start_date w dateTime

Revision ID: 8814bf1b42fe
Revises: 69e38aa57210
Create Date: 2025-05-20 10:52:15.265967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8814bf1b42fe'
down_revision = '69e38aa57210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_preferences')
    with op.batch_alter_table('logged_week', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_week', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)

    op.create_table('workout_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='workout_preferences_user_id_key')
    )
    # ### end Alembic commands ###
