"""Updated saved plan structure to relational format

Revision ID: 882df195d237
Revises: 5f1e20bb9db0
Create Date: 2025-04-27 13:58:39.140077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882df195d237'
down_revision = '5f1e20bb9db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plan', schema=None) as batch_op:
        batch_op.drop_constraint('saved_plan_plan_key', type_='unique')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('saved_plan_plan_key', ['plan'])

    # ### end Alembic commands ###
