"""Initial migration

Revision ID: 8d9bdb5f23b5
Revises: 
Create Date: 2025-04-23 09:44:14.008501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9bdb5f23b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_muscles', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('secondary_muscles', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('secondary_muscles')
        batch_op.drop_column('primary_muscles')

    # ### end Alembic commands ###
