"""Add Note model and update SavedExercise

Revision ID: baf6600c8ab8
Revises: 5761b37f8410
Create Date: 2025-04-28 13:12:52.772705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf6600c8ab8'
down_revision = '5761b37f8410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
