"""Made logged set info nullable

Revision ID: d5f6c673a0df
Revises: 2b32b334fd2d
Create Date: 2025-05-20 12:27:40.573938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f6c673a0df'
down_revision = '2b32b334fd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_preferences')
    with op.batch_alter_table('logged_set', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_set', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('workout_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workout_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='workout_preferences_user_id_key')
    )
    # ### end Alembic commands ###
