"""Remove plan column from SavedPlan

Revision ID: dd75128522f5
Revises: 3d6605fedb7d
Create Date: 2025-04-27 14:16:55.093544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd75128522f5'
down_revision = '3d6605fedb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plan', schema=None) as batch_op:
        batch_op.drop_column('plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
