"""Convert equipment to enum

Revision ID: e09f9c8b43c7
Revises: 
Create Date: 2025-04-23 16:41:53.248206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09f9c8b43c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_role_association', schema=None) as batch_op:
        batch_op.drop_constraint('day_role_association_exercise_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise_role', ['exercise_role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_role_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('day_role_association_exercise_role_id_fkey', 'exercise_role', ['exercise_role_id'], ['id'])

    # ### end Alembic commands ###
